# Generated by Django 4.1.7 on 2023-02-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_contact_us_alter_user_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='Authentication/food_images')),
                ('item_detail', models.TextField()),
            ],
        ),
    ]
