# Generated by Django 4.1.7 on 2023-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0006_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('contact_1', models.CharField(max_length=10, unique=True)),
                ('contact_2', models.CharField(max_length=10, unique=True)),
                ('mail_1', models.EmailField(max_length=254, unique=True)),
                ('mail_2', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
