# Generated by Django 4.1.7 on 2023-03-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0008_gallary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_title', models.CharField(max_length=30)),
                ('feature_description', models.TextField()),
                ('feature_image', models.ImageField(upload_to='feature_images/')),
            ],
        ),
    ]
