# Generated by Django 4.1.7 on 2023-03-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0011_remove_user_info_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
